name: pyalign
channels:
  - default
  - conda-forge
dependencies:
  - python=3.8
  - xtl
  - xtensor
  - xsimd
  - xtensor-blas
  - xtensor-python
  - pip
  - pip:
      - numpy~=1.19
      - pybind11~=2.6.2
      - cached_property
      - cpufeature==0.2.0
      - pymorton==1.0.5
